version: '2'
services:
  storage:
    image: meridor/perspective-storage:${VERSION}
  rest:
    image: meridor/perspective-rest:${VERSION}
    ports:
     - "8080:8080"    
    links:
      - storage
    environment:
      - MISC_PROPERTIES=-Dperspective.storage.hosts=storage:5801
  openstack:
    image: meridor/perspective-openstack:${VERSION}
    links:
      - storage
    environment:
      - MISC_PROPERTIES=-Dperspective.storage.hosts=storage:5801
    depends_on:
      - rest
  docker:
    image: meridor/perspective-docker:${VERSION}
    links:
      - storage
    environment:
      - MISC_PROPERTIES=-Dperspective.storage.hosts=storage:5801
    depends_on:
      - rest